config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :settings

  resources :appointments

  get 'appointments/by-date/:appt_date' => 'appointments#by_date', :as => 'appointments_by_date'

  get '/calendar' => 'calendar#show'

  get 'reps/show'

  get 'profiles/reset_password/:id' => 'profiles#reset_password', :as => 'reset_user_password'
  resources :profiles

  namespace :profiles do
    namespace :move do
      get  :new
      post :create
    end
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # devise_for :users, :skip => [:registrations]

  # https://github.com/plataformatec/devise#configuring-controllers
  devise_for :users, controllers: { sessions: 'users/sessions' }, :skip => [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :activities do
    get :autocomplete_client_name, :on => :collection
  end

  resources :models

  resources :industries

  resources :clients do
    resources :contacts
  end
  resources :outsiders
  get 'prospects/unassigned' => 'prospects#unassigned'
  get 'prospects/assignedoutsider' => 'prospects#assignedoutsider'
  get 'prospects/assignedrsm' => 'prospects#assignedrsm'
  get 'prospects/assignedcurrentrsm' => 'prospects#assignedcurrentrsm'
  resources :prospects do
    get :autocomplete_outsider_email, :on => :collection
    resources :contacts
    resources :outsiders
    resources :rsms
  end

  get 'prospects/convert_to_client/:id' => 'prospects#convert_to_client', :as => 'convert_prospect_to_client'
  get 'clients/archive/:id' => 'clients#archive', :as => 'archive_client'
  get 'clients/unarchive/:id' => 'clients#un_archive', :as => 'un_archive_client'
  get 'clients-archived' => 'clients#index_archived', :as => 'archived_clients'
  get 'clients/:id/reps/:user_id' => 'clients#show'
  root 'activities#index'
  get 'clients/:id/add-rsm-to-client' => 'clients#add_rsm_to_client', :as => 'add_rsm_to_client'
  get 'clients/:id/remove_rsm_from_client' => 'clients#remove_rsm_from_client', :as => 'remove_rsm_from_client'
  get 'prospects/:id/remove_rsm_from_prospect' => 'prospects#remove_rsm_from_prospect', :as => 'remove_rsm_from_prospect'
  get '/auditlogs' => 'audit_logs#index'

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  time_zone  :string
#

class Profile < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :user_id

  def admin
    self.user.admin
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/profiles/move_controller.rb
class Profiles::MoveController < ApplicationController

  def new
    if !current_user.admin?
      redirect_to profiles_path, :alert => "Not authorized. Only admins can access this function"
    end
  end

  def create
    if current_user.admin?
      if valid_params[:from].empty? || valid_params[:to].empty?
        redirect_to profiles_move_new_path, :alert => "Oops! You need to choose both a FROM and a TO RSM. Please retry or cancel."
      elsif valid_params[:from] == valid_params[:to]
        redirect_to profiles_move_new_path, :alert => "Oops! You chose the same user for the from and to value. Please retry or cancel."
      else
        @user_from = User.find(valid_params[:from])
        if @user_from.clients.size == 0
          redirect_to profiles_path, :alert => "#{@user_from.user_name} doesn't have any clients. No clients moved."
        else
          @user_to = User.find(valid_params[:to])
          @unique_clients = @user_from.clients - @user_to.clients
          @user_to.clients << @unique_clients # only add the different clients - avoid dupes
          @user_from.clients = []
          redirect_to profiles_path, :notice => "#{@user_from.user_name}'s clients were moved to #{@user_to.user_name}."
        end
      end
    else
      redirect_to profiles_path, :alert => "Not authorized. Only admins can access this function"
    end
  end

  private

  def valid_params
    params.permit(:from,:to)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_tab
  respond_to :html

  def index
    if current_user.admin?
      @profiles = Profile.all.order(:first_name)
      respond_with(@profiles)
    else
      redirect_to root_path, :alert => "Not authorized. Only administrators can view RSM's."
    end
  end

  def new
    if current_user.admin?
      @profile = Profile.new
    else
      redirect_to root_path, :alert => "Not authorized. Only administrators can create new RSM's."
    end
  end

  def show
    @user = @profile.user
    if current_user.admin?
      if params[:search_activities].nil?
        @profile_activities = @user.activities.order("activity_date DESC").page params[:page]
      else
        @profile_activities = @user.activities.search_activities(params[:search_activities]) # => [person_1, person_2]
      end
      @rsm_clients = @user.active_clients
      @rsm_prospects = @user.active_prospects
    else
      redirect_to root_path, :alert => "Not authorized. Only administrators can view RSM's."
    end
  end

  def edit
    if !current_user.admin?
      redirect_to root_path, :alert => "Not authorized. Only administrators can create edit RSM's."
    end
  end

  def create
    @profile = Profile.new(profile_params)
    if !current_user.admin?
      redirect_to profiles_path, :alert => "Only administrators can create new RSM's."
    elsif params["password"] != params["password_confirmation"]
      redirect_to :back, :alert => "Your passwords don't match"
    elsif params[:email].blank? || profile_params["first_name"].blank? || profile_params["last_name"].blank?
      redirect_to :back, :alert => "All fields are required. Please try again."
    else
      @user = User.new(:admin => params[:admin], :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation])
      if @user.save
        @profile = @user.profile
        @profile.update_attributes(profile_params)
        redirect_to profiles_path
      else
        @user.errors.full_messages.each do |msg|
          @profile.errors.add(:base,msg)
        end
        render :action => :new
      end
    end
  end

  def update
    if current_user.admin?
      @user = @profile.user
      if password_changed? && password_valid?
        admin = profile_params["admin"] == "1" ? true : false
        @user.update(user_params.merge(:admin => admin))
        @profile.update(:first_name => profile_params[:first_name], :last_name => profile_params[:last_name], :time_zone => profile_params[:time_zone])
        redirect_to profiles_path, :notice => "Profile and password updated."
      elsif password_changed? && password_invalid?
        render :edit
      else
        admin = profile_params["admin"] == "1" ? true : false
        @user.update(:admin => admin)
        @profile.update(:first_name => profile_params[:first_name], :last_name => profile_params[:last_name], :time_zone => profile_params[:time_zone])
        redirect_to profiles_path, :notice => "Profile updated."
      end
    else
      redirect_to profiles_path, :alert => "Unauthorized. Only admins can update profiles."
    end
  end

  def destroy
    @profile.destroy
    redirect_to profiles_path
  end

  def reset_password
    if current_user.admin?
      @profile = Profile.find(params[:id])
      @user = @user
      @user.send_reset_password_instructions
      redirect_to profiles_path, :alert => "You have successfully reset the password for #{@profile.first_name} #{@profile.last_name}. They have been sent reset instructions via email."
    else
      redirect_to profiles_path, :alert => "You are not authorized to reset passwords for RSM's."
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def set_tab
    @tab = "RSM's"
  end

  def password_changed?
    user_params[:password].present? || user_params[:password_confirmation].present?
  end

  def password_valid?
    return false if user_params[:password] != user_params[:password_confirmation]
    return false if user_params[:password].length < 8
    return true
  end

  def password_invalid?
    if user_params[:password] != user_params[:password_confirmation]
      @profile.errors[:base] << "The passwords don't match. Please retry."
      return true
    end
    if user_params[:password].length < 8
      @profile.errors[:base] << "The password is too short. It needs to be at least 8 characters long."
      return true
    end
    return false
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :user_id, :admin, :role, :time_zone)
  end

  def user_params
    params.require(:profile).permit(:password,:password_confirmation)
  end

end

app/views/profiles/_form.html.erb
<%= form_for @profile, :html => {:class => "form", :role => "form"}  do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :time_zone, "Show times to this user in this time zone" %><br />
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: "Eastern Time (US & Canada)" %>
  </div>
  <% if current_user.admin? %>
    <div class="form-group">
      <%= f.label :password, 'New password' %> <i>(<%= t('.leave_blank_if_you_don_t_want_to_change_it', :default => "leave blank if you don't want to change it") %>)</i>
      <%= f.password_field :password, :autocomplete => "off", :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'New password confirmation' %>
      <%= f.password_field :password_confirmation, :class => "form-control"  %>
    </div>
  <% end %>
  <% if current_user.admin? %>
    <div class="form-group">
      <div class="checkbox">
        <label>
          <%= f.check_box :admin %>
          <%= f.label :admin %>
        </div>
      <% end %>
      <div class="form-group">
        <%= button_tag(type: 'submit', :class => "btn btn-primary") do %>
          <i class="fas fa-check"></i> Save
    <% end %>
        <%= link_to :back, :class => "btn btn-default" do %>
          <i class="fas fa-times"></i> Cancel
    <% end %>
      </div>
    <% end %>

app/views/profiles/edit.html.erb
<h2>Editing RSM</h2>
<p><%= link_to @profile.user.email, "mailto:#{@profile.user.email}" %></p>
<%= render 'form' %>

app/views/profiles/index.html.erb
<h2>RSM's</h2>
<% if current_user.admin? %>
  <p>
    <%= link_to new_profile_path, :class => "btn btn-primary" do %>
      <i class="fas fa-plus"></i> Add RSM
    <% end %>
    <%= link_to profiles_move_new_path, :class => "btn btn-primary" do %>
      <i class="fas fa-arrow-right"></i> Move clients from one RSM to another
    <% end %>
  </p>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td style="vertical-align:middle;">
          <% if profile.first_name == "" %>
            <%= link_to "No name defined yet", profile %>
          <% else %>
            <%= link_to "#{profile.first_name} #{profile.last_name}", profile %>
          <% end %>
          <% if profile.admin %>
            *Admin
          <% end %>
          <% if profile.user.marketing? %>
            *Marketing
          <% end %>
        </td>
        <td style="vertical-align:middle;"><%= profile.user.email %></td>
        <td style="vertical-align:middle;">
          <% if profile.user == current_user || current_user.admin? %>
            <%= link_to edit_profile_path(profile), :class => "btn btn-primary" do %>
              <i class="fas fa-pencil-alt"></i> Edit
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h2>New RSM</h2>
<%= form_for @profile, :html => {:class => "form", :role => "form"}  do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag 'email', "", class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :password %><br>
    <%= password_field_tag "password", "", :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag :password_confirmation %><br>
    <%= password_field_tag "password_confirmation", "", :class => "form-control" %>
  </div>
  <% if current_user.admin? %>
    <div class="form-group">
      <%= check_box_tag "Admin" %>
      <%= label_tag :admin %>
    </div>
  <% end %>
  <div class="form-group">
    <%= button_tag(type: 'submit', :class => "btn btn-primary") do %>
      <i class="fas fa-check"></i> Save
    <% end %>
    <%= link_to :back, :class => "btn btn-default" do %>
      <i class="fas fa-times"></i> Cancel
    <% end %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<h2><%= "#{@profile.first_name} #{@profile.last_name}" %></h2>
<p>
  <%= link_to @profile.user.email, "mailto:#{@profile.user.email}" %>
  <% if @profile.admin %>
    *Admin
  <% end %>
  <% if @profile.user.marketing? %>
    *Marketing
  <% end %>
</p>
<% if current_user == @profile.user %>
  <p>If necessary...<%= link_to "change your password", edit_user_registration_path %></p>
<% end %>
<p>
  <% if @profile.user == current_user || current_user.admin? %>
    <%= link_to edit_profile_path(@profile), :class => "btn btn-primary" do %>
      <i class="fas fa-pencil-alt"></i> Edit
    <% end %>
  <% end %>
  <%= link_to :back, :class => "btn btn-default" do %>
    <i class="fas fa-chevron-left"></i> Back
  <% end %>
</p>
<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="#activities" aria-controls="activities" role="tab" data-toggle="tab">Activities</a></li>
  <li role="presentation"><a href="#clients" aria-controls="clients" role="tab" data-toggle="tab">Clients</a></li>
  <li role="presentation"><a href="#prospects" aria-controls="prospects" role="tab" data-toggle="tab">Prospects</a></li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="activities">
    <% if @profile_activities.any? %>
      <% if !params[:search_activities].nil? %>
        <p><%= "Found #{pluralize(@profile_activities.count, 'activity')} matching '#{params[:search_activities]}'" %><br/>
          <%= link_to 'Clear search results', @profile %>
        </p>
      <% end %>
      <% if @profile_activities.count > 1 %>
        <p><%= form_tag @profile, :method => 'get' do %>
            <%= search_field_tag :search_activities, params[:search_activities], :placeholder => "search activities" %>
          <% end %></p>
      <% end %>
      <% @profile_activities.order("activity_date DESC").each do |activity| %>
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <%= link_to activity.activity_date.to_date, activity %>
            <% if activity && activity.activity_attachments.empty? && activity.attachment_url.present? %>
              <i class="fas fa-paperclip"></i>
            <% end %>
            <% activity.activity_attachments.each do %>
              <i class="fas fa-paperclip"></i>
            <% end %>
          </div>
          <div class="panel-body">
            <p>
              <%= activity.client.name %>:
              <% if !activity.contact.nil? %>
                <%= activity.contact.name %><br>
              <% end %>
              <%= activity.comments %><br>
              <% if current_user.admin? && params[:user_id].nil? %>
                Submitted by <%= activity.user_name %> on <%= activity.created_at.strftime("%m/%d/%Y %I:%M %P %Z") %>
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    <% else %>
      <h2>No activities yet</h2>
    <% end %>
    <% if params[:search_activities].nil? %>
      <div style="background:#F5F5F5;padding:0 10px;border-radius:5px;">
        <%= paginate @profile_activities %>
      </div>
    <% end %>
  </div>

  <div role="tabpanel" class="tab-pane" id="clients">
    <% if @rsm_clients.any? %>
      <h2><%= @profile.user.user_name %>'s active clients</h2>
      <table>
        <% @rsm_clients.order(:name,:city).each do |client| %>
          <tr>
            <td style="padding:10px;">
              <li><%= link_to "#{client.name} (#{client.location})", client %></li>
            </td>
            <td>
              <% if current_user == @profile.user || current_user.admin? %>
                <%= link_to remove_rsm_from_client_path(client,:user_id => @profile.user), :class => "btn btn-default", data: { confirm: "Remove this client from this list? Are you sure?" } do %>
                  <i class="fas fa-times"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <div role="tabpanel" class="tab-pane" id="prospects">
    <% if @rsm_prospects.any? %>
      <h2><%= @profile.user.user_name %>'s prospects</h2>
      <table>
        <% @rsm_prospects.order(:name,:city).each do |prospect| %>
          <tr>
            <td style="padding:10px;">
              <li><%= link_to "#{prospect.name} (#{prospect.location})", prospect_path(prospect) %></li>
            </td>
            <td>
              <% if current_user == @profile.user || current_user.admin? %>
                <%= link_to remove_rsm_from_prospect_path(prospect,:user_id => @profile.user), :class => "btn btn-default", data: { confirm: "Remove this prospect from this list? Are you sure?" } do %>
                  <i class="fas fa-times"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>