config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :settings

  resources :appointments

  get 'appointments/by-date/:appt_date' => 'appointments#by_date', :as => 'appointments_by_date'

  get '/calendar' => 'calendar#show'

  get 'reps/show'

  get 'profiles/reset_password/:id' => 'profiles#reset_password', :as => 'reset_user_password'
  resources :profiles

  namespace :profiles do
    namespace :move do
      get  :new
      post :create
    end
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # devise_for :users, :skip => [:registrations]

  # https://github.com/plataformatec/devise#configuring-controllers
  devise_for :users, controllers: { sessions: 'users/sessions' }, :skip => [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :activities do
    get :autocomplete_client_name, :on => :collection
  end

  resources :models

  resources :industries

  resources :clients do
    resources :contacts
  end
  resources :outsiders
  get 'prospects/unassigned' => 'prospects#unassigned'
  get 'prospects/assignedoutsider' => 'prospects#assignedoutsider'
  get 'prospects/assignedrsm' => 'prospects#assignedrsm'
  get 'prospects/assignedcurrentrsm' => 'prospects#assignedcurrentrsm'
  resources :prospects do
    get :autocomplete_outsider_email, :on => :collection
    resources :contacts
    resources :outsiders
    resources :rsms
  end

  get 'prospects/convert_to_client/:id' => 'prospects#convert_to_client', :as => 'convert_prospect_to_client'
  get 'clients/archive/:id' => 'clients#archive', :as => 'archive_client'
  get 'clients/unarchive/:id' => 'clients#un_archive', :as => 'un_archive_client'
  get 'clients-archived' => 'clients#index_archived', :as => 'archived_clients'
  get 'clients/:id/reps/:user_id' => 'clients#show'
  root 'activities#index'
  get 'clients/:id/add-rsm-to-client' => 'clients#add_rsm_to_client', :as => 'add_rsm_to_client'
  get 'clients/:id/remove_rsm_from_client' => 'clients#remove_rsm_from_client', :as => 'remove_rsm_from_client'
  get 'prospects/:id/remove_rsm_from_prospect' => 'prospects#remove_rsm_from_prospect', :as => 'remove_rsm_from_prospect'
  get '/auditlogs' => 'audit_logs#index'

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id              :integer          not null, primary key
#  name            :string
#  street1         :string
#  street2         :string
#  city            :string
#  state           :string
#  zip             :string
#  phone           :string
#  industry        :string
#  created_at      :datetime
#  updated_at      :datetime
#  fax             :string
#  street3         :string
#  client_type     :string
#  status          :text
#  eid             :string
#  prospect_type   :text
#  source          :text
#  form_dump       :text
#  import_datetime :datetime
#  comments        :text
#  country         :string
#

class Client < ActiveRecord::Base

  before_save :default_values, :trim_spaces_from_name
  has_many :activities, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_and_belongs_to_many :users
  has_and_belongs_to_many :outsiders
  validates :name, :presence => true

  def archived?
    if self.status == "Archived"
      return true
    else
      return false
    end
  end

  def google_maps_address
    if street1.present?
      address = [name,street1,street2,city,state,zip].join(" ")
      return "http://maps.google.com/?q=#{ERB::Util.url_encode(address)}"
    else
      return ""
    end
  end

  def location
    if self.city.present? && self.state.present? && self.country.present?
      return [self.city,self.state].join(", ") + " (#{self.country})"
    elsif self.city.present? && self.state.present?
      return [self.city,self.state].join(", ")
    elsif !self.state.present? && self.city.present?
      return self.city
    else
      return "no location defined"
    end
  end

  def name_and_location
    location = self.location
    if location == "no location defined"
      return name
    else
      return "#{name} (#{location})"
    end
  end

  def default_values
    self.client_type ||= 'Client'
    self.status ||= 'Active'
  end

  def trim_spaces_from_name
    self.name = self.name.strip
  end

  def self.as_csv
    CSV.generate do |csv|
      x = column_names + ["contacts_email", "users_email"]
      csv << x
      all.each do |item|
        y = item.attributes.values_at(*column_names) + [item.contacts.pluck("email").join(",")] + [item.users.pluck("email").join(",")]
        csv << y
      end
    end
  end

  def self.unassigned_prospects
    self.where(client_type:'Prospect').where(status:'Active').includes(:users).where(users:{id: nil}).includes(:outsiders).where(outsiders:{id: nil})
  end

  def self.assigned_prospects_to_rsms
    self.where(client_type:'Prospect').where(status:'Active').includes(:users).where.not(users:{id: nil})
  end

  def self.assigned_prospects_to_outsiders
    self.where(client_type:'Prospect').where(status:'Active').includes(:outsiders).where.not(outsiders:{id: nil})
  end

  def self.import_prospects_via_json(json)
    if valid_json?(json)
      parsed_response = JSON.parse(json)
      parsed_response.each do |data|
        import_eid = data["EID"]
        import_date = data["Date"]
        import_type = data["Type"]
        import_source = data["Source"]
        import_company = data["Company"].force_encoding('Windows-1252').encode('UTF-8')
        import_contactname = data["ContactName"].force_encoding('Windows-1252').encode('UTF-8')
        import_phone = data["Phone"]
        import_fax = data["Fax"]
        import_email = data["Email"]
        import_street = data["Address"][0]["Street"].force_encoding('Windows-1252').encode('UTF-8')
        import_city = data["Address"][0]["City"].force_encoding('Windows-1252').encode('UTF-8')
        import_state = data["Address"][0]["State"].force_encoding('Windows-1252').encode('UTF-8')
        import_country = data["Address"][0]["Country"].force_encoding('Windows-1252').encode('UTF-8')
        import_zip = data["Address"][0]["ZipCode"]
        import_formdump = data["FormDump"].force_encoding('Windows-1252').encode('UTF-8')
        existing_client = Client.find_by_eid(import_eid)
        import_datetime = DateTime.strptime(import_date + " EST", '%Y-%m-%d %R %Z')
        if import_company == "1" || import_company == "-1"
          puts "Skipping EID = #{import_eid} for client #{import_company}. Junk data"
        elsif import_datetime >= "2015-12-01".to_date
          if existing_client.nil? && import_company.present?
            # create a new one - assume EST
            new_client = Client.create!(
              :eid => import_eid,
              :name => import_company,
              :street1 => import_street,
              :city => import_city,
              :state => import_state,
              :zip => import_zip,
              :country => import_country,
              :import_datetime => import_datetime,
              :prospect_type => import_type,
              :source => import_source,
              :form_dump => import_formdump,
              :client_type => "Prospect",
              :status => "Active",
              :fax => import_fax
            )
            contact_params = {name: import_contactname, work_phone: import_phone, email: import_email}
            new_contact = Contact.create_from_import(contact_params)
            new_client.contacts << new_contact
            puts "Imported #{new_client.name}"
          else
            puts "Skipping EID = #{import_eid} for client #{import_company}. Already in DB by EID"
          end
        else
          puts "Skipping EID = #{import_eid} for client #{import_company}. Import date of #{import_date} is too old."
        end
        rescue Encoding::UndefinedConversionError
          UserMailer.notify_on_encoding_error_during_import(json).deliver_now
          next
      end
    else
      UserMailer.notify_on_invalid_json(json).deliver_now
    end
  end

  def self.valid_json?(json)
    JSON.parse(json)
    return true
  rescue JSON::ParserError
    return false
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :hide_from_marketing
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :set_tab

  def archive
    if current_user.admin?
      @client = Client.find(params[:id])
    else
      @client = current_user.clients.find(params[:id])
    end
    @client.status = "Archived"
    @client.save!
    redirect_to @client, :notice => "This client has been archived. You may un-archive later if you need to."
  end

  def un_archive
    if current_user.admin?
      @client = Client.find(params[:id])
    else
      @client = current_user.clients.find(params[:id])
    end
    @client.status = "Active"
    @client.save!
    redirect_to @client, :notice => "This client has been un-archived and set to active."
  end

  def index_archived
    if current_user.admin?
      @clients = Client.where(status: 'Archived').where.not(client_type: 'Prospect')
    else
      @clients = current_user.clients.where(status: 'Archived').where.not(client_type: 'Prospect')
    end
    if params[:search].present?
      @clients = @clients.where('lower(name) LIKE ?', "%#{params[:search].downcase}%").order(:name, :city)
    else
      @clients = @clients.order(:name, :city)
    end
  end

  def index
    if current_user.admin?
      @clients = Client.where(status: 'Active').where.not(client_type: 'Prospect').page params[:page]
    else
      @clients = current_user.clients.where(status: 'Active').where.not(client_type: 'Prospect').page params[:page]
    end
    if params[:search_state].present?
      @clients = @clients.where('lower(state) LIKE ?', "%#{params[:search_state].downcase}%").order(:name, :city)
    elsif params[:search_name].present?
      @clients = @clients.where('lower(name) LIKE ?', "%#{params[:search_name].downcase}%").order(:name, :city)
    elsif params[:search_city].present?
      @clients = @clients.where('lower(city) LIKE ?', "%#{params[:search_city].downcase}%").order(:name, :city)
    elsif params[:search_zip].present?
      @clients = @clients.where('lower(zip) LIKE ?', "%#{params[:search_zip].downcase}%").order(:name, :zip)
    elsif params[:search_phone].present?
      @clients = @clients.where('lower(phone) LIKE ?', "%#{params[:search_phone].downcase}%").order(:name, :city)
    elsif params[:search].present?
      @clients = @clients.where('lower(name) LIKE ?', "%#{params[:search].downcase}%").order(:name, :city)
    else
      @clients = @clients.order(:name, :city)
    end
  end

  def show
    if current_user.admin? || current_user.clients.include?(@client)
      if params[:user_id]
        @rep_activities = @client.activities.where(:user_id => params[:user_id])
      else
        @rep_activities = @client.activities
      end
      respond_to do |format|
        format.html
        format.json { render json: @client.to_json(include: :contacts) }
      end
    else
      redirect_to clients_path, :alert => "Unauthorized. Only admins and RSM's connected to this client can see this client"
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        @client.users << current_user
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # Admins can delete but users can only request
  def destroy
    if current_user.admin?
      @client.destroy
      redirect_to clients_url, notice: 'Client was successfully destroyed.'
    else
      @recipients = Setting.get_notify_on_client_delete_recipients
      if !@recipients.present?
        @recipients = "dalmeida@mixers.com"
      end
      UserMailer.notify_on_client_delete(@client,@recipients,current_user).deliver_now
      redirect_to @client, notice: "An email was sent to #{@recipients} about your request to delete this client."
    end
  end

  def add_rsm_to_client
    @client = Client.find(params[:id])
    if params[:user_id].nil?
      @profiles = Profile.all.order(:first_name,:last_name)
    else
      @user = User.find(params[:user_id])
      @client.users << @user
      redirect_to @client, notice: "#{@user.user_name} was added to this client."
    end
  end

  def remove_rsm_from_client
    @client = Client.find(params[:id])
    @user = User.find(params[:user_id])
    if current_user.admin?
      @client.users.delete(@user)
      redirect_to @user.profile, notice: "Removed #{@client.name} from #{@user.user_name}'s list of clients"
    else
      if current_user == @user
        @client.users.delete(current_user)
        redirect_to @user.profile, notice: "Removed #{@client.name} from your list of clients"
      else
        redirect_to @user.profile, alert: "Only admin's can remove clients from users' profiles."
      end
    end
  end

  private
  def hide_from_marketing
    if current_user.marketing? && !current_user.admin?
      redirect_to prospects_path, :alert => "Not authorized. Users who are in the marketing role may not access clients."
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  def set_tab
    @tab = "Client"
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:name, :country, :comments, :street1, :street2, :city, :state, :zip, :phone, :industry)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, :html => {:class => "form", :role => "form"} do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :street1 %>
    <%= f.text_field :street1, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :street2 %>
    <%= f.text_field :street2, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :street3 %>
    <%= f.text_field :street3, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.select :state, options_for_select(us_states,@client.state), {:include_blank => true}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :zip %>
    <%= f.text_field :zip, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :fax %>
    <%= f.text_field :fax, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :industry %>
    <%= f.select :industry, options_from_collection_for_select(Industry.all.order(:name), :id, :name, @client.industry), {:include_blank => true}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, :class => "form-control", :rows => "3" %>
  </div>
  <div class="form-group">
    <%= button_tag(type: 'submit', :class => "btn btn-primary") do %>
      <i class="fas fa-check"></i> Save
    <% end %>
    <%= link_to clients_path, :class => "btn btn-default" do %>
      <i class="fas fa-times"></i> Cancel
    <% end %>
  </div>
<% end %>

app/views/clients/add_rsm_to_client.html.erb
<h2>Choose RSM for <%= @client.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td>
          <% if profile.first_name == "" %>
            <%= link_to "No name defined yet", profile %>
          <% else %>
            <%= link_to "#{profile.first_name} #{profile.last_name}", profile %>
          <% end %>
          <% if profile.admin %>
            *Admin
          <% end %>
        </td>
        <td><%= profile.user.email %></td>
        <td>
          <% if @client.users.include?(profile.user) %>
            Already added
          <% else %>
            <%= link_to add_rsm_to_client_path(@client,:user_id => profile.user), :class => "btn btn-primary" do %>
              <i class="fas fa-plus"></i>
              Add this RSM to client
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to :back, :class => "btn btn-default" do %>
  <i class="fas fa-chevron-left"></i> Cancel
<% end %>

app/views/clients/edit.html.erb
<h2>Editing client</h2>

<%= render 'form' %>

app/views/clients/index.html.erb
<h2>Active Clients</h2>
<p><%= link_to "View archived clients", archived_clients_path %></p>
<p><%= link_to 'New Client', new_client_path, :class => "btn btn-primary" %></p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>City</th>
      <th>Zip</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= form_tag clients_path, :method => 'get' do %>
        <%= search_field_tag :search_name, params[:search_name], :placeholder => "search" %>
        <% end %></td>
      <td><%= form_tag clients_path, :method => 'get' do %><%= search_field_tag :search_state, params[:search_state], :placeholder => "search" %><% end %></td>
      <td><%= form_tag clients_path, :method => 'get' do %><%= search_field_tag :search_city, params[:search_city], :placeholder => "search" %><% end %></td>
      <td><%= form_tag clients_path, :method => 'get' do %><%= search_field_tag :search_zip, params[:search_zip], :placeholder => "search" %><% end %></td>
      <td><%= form_tag clients_path, :method => 'get' do %><%= search_field_tag :search_phone, params[:search_phone], :placeholder => "search" %><% end %></td>
    </tr>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.name, client %></td>
        <td><%= client.state %></td>
        <td><%= client.city %></td>
        <td><%= client.zip %></td>
        <td><%= client.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div style="background:#F5F5F5;padding:0 10px;border-radius:5px;">
  <%= paginate @clients %>
</div>

app/views/clients/index_archived.html.erb
<h2>Archived Clients</h2>
<p><%= link_to "View active clients", clients_path %></p>

<p>Click column header to sort</p>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>City</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.name, client %></td>
        <td><%= client.state %></td>
        <td><%= client.city %></td>
        <td><%= client.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(function(){
    $(".table").tablesorter();
  });
</script>

app/views/clients/new.html.erb
<h2>New client</h2>

<%= render 'form' %>

app/views/clients/show.html.erb
<h2><%= @client.name %><% if @client.archived? %> (Archived)<% end %></h2>
<table class="table">
  <tr>
    <td>Phone</td>
    <td><%= @client.phone %></td>
  </tr>
  <tr>
    <td>Fax</td>
    <td><%= @client.fax %></td>
  </tr>
  <tr>
    <td>Street 1</td>
    <td><%= @client.street1 %></td>
  </tr>
  <tr>
    <td>Street 2</td>
    <td><%= @client.street2 %></td>
  </tr>
  <tr>
    <td>Street 3</td>
    <td><%= @client.street3 %></td>
  </tr>
  <tr>
    <td>City</td>
    <td><%= @client.city %></td>
  </tr>
  <tr>
    <td>State</td>
    <td><%= @client.state %></td>
  </tr>
  <tr>
    <td>Zip</td>
    <td><%= @client.zip %></td>
  </tr>
  <tr>
    <td>Country</td>
    <td><%= @client.country %></td>
  </tr>
  <tr>
    <td>Industry</td>
    <td><%= @client.industry.nil? || @client.industry == "" ? "" : Industry.find(@client.industry).name %></td>
  </tr>
  <tr>
    <td>Comments</td>
    <td><%= @client.comments %></td>
  </tr>
  <tr>
    <td>Created</td>
    <td><%= @client.created_at.strftime("%m/%d/%Y %I:%M %P %Z") %></td>
  </tr>
  <% if @client.created_at.to_i != @client.updated_at.to_i %>
    <tr>
      <td>Updated</td>
      <td><%= @client.updated_at.strftime("%m/%d/%Y %I:%M %P %Z") %></td>
    </tr>
  <% end %>
  <% if !@client.eid.nil? %>
    <tr>
      <td>EID</td>
      <td><%= @client.eid %></td>
    </tr>
    <tr>
      <tr>
        <td>Import Time</td>
        <td><%= @client.import_datetime.strftime("%m/%d/%Y %I:%M %P %Z") %></td>
      </tr>
      <tr>
        <tr>
          <td>Type</td>
          <td><%= @client.prospect_type %></td>
        </tr>
        <tr>
          <td>Source</td>
          <td><%= @client.source %></td>
        </tr>
        <tr>
          <td>From Web Form</td>
          <td><%= sanitize @client.form_dump %></td>
        </tr>
      <% end %>
    </table>
    <p>
      <% if @client.status != "Archived" %>
        <%= link_to edit_client_path(@client), :class => "btn btn-primary" do %>
          <i class="fas fa-pencil-alt"></i> Edit
    <% end %>
        <%= link_to new_activity_path(:client => @client), :class => "btn btn-primary" do %>
          <i class="fas fa-plus"></i> Add Activity
    <% end %>
        <%= link_to new_client_contact_path(@client), :class => "btn btn-primary" do %>
          <i class="fas fa-plus"></i> Add Contact
    <% end %>
        <%= link_to add_rsm_to_client_path(@client), :class => "btn btn-primary" do %>
          <i class="fas fa-plus"></i> Add RSM
    <% end %>
        <%= link_to archive_client_path(@client), :class => "btn btn-primary" do %>
          <i class="fas fa-archive"></i> Archive
    <% end %>
        <%= link_to client_path(@client), :method => :delete, :data => { confirm: 'Are you sure?' }, :class => "btn btn-primary" do %>
          <i class="fas fa-trash-alt"></i> Delete
    <% end %>
      <% end %>
      <% if @client.status == "Archived" %>
        <%= link_to un_archive_client_path(@client), :class => "btn btn-primary" do %>
          <i class="fas fa-archive"></i> UnArchive
    <% end %>
      <% end %>
      <%= link_to :back, :class => "btn btn-default" do %>
        <i class="fas fa-chevron-left"></i> Back
  <% end %>
    </p>
    <% if @client.contacts.present? %>
      <h2>Contacts for this client</h2>
      <ul>
        <% @client.contacts.each do |contact| %>
          <li><%= link_to contact.name, [@client,contact] %></li>
        <% end %>
      </ul>
    <% end %>
    <% if @client.users.present? %>
      <h2>RSM's for this client</h2>
      <ul>
        <% @client.users.each do |user| %>
          <li><%= link_to user.user_name, user.profile %></li>
        <% end %>
      </ul>
    <% end %>
    <% if @rep_activities.any? %>
      <h2>Activities for this Client <%= params[:user_id] ? "by #{User.find(params[:user_id]).user_name}" : "" %></h2>
      <% @rep_activities.order("activity_date DESC").each do |activity| %>
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <%= link_to activity.activity_date.to_date, activity %>
            <% if activity && activity.activity_attachments.empty? && activity.attachment_url.present? %>
              <i class="fas fa-paperclip"></i>
            <% end %>
            <% activity.activity_attachments.each do %>
              <i class="fas fa-paperclip"></i>
            <% end %>
          </div>
          <div class="panel-body">
            <p>
              <%= activity.client.name %>:
          <% if !activity.contact.nil? %>
                <%= activity.contact.name %><br>
              <% end %>
              <%= activity.comments %><br>
              <% if current_user.admin? && params[:user_id].nil? %>
                Submitted by <%= activity.user_name %> on <%= activity.created_at.strftime("%m/%d/%Y %I:%M %P %Z") %>
              <% end %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>