config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :settings

  resources :appointments

  get 'appointments/by-date/:appt_date' => 'appointments#by_date', :as => 'appointments_by_date'

  get '/calendar' => 'calendar#show'

  get 'reps/show'

  get 'profiles/reset_password/:id' => 'profiles#reset_password', :as => 'reset_user_password'
  resources :profiles

  namespace :profiles do
    namespace :move do
      get  :new
      post :create
    end
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # devise_for :users, :skip => [:registrations]

  # https://github.com/plataformatec/devise#configuring-controllers
  devise_for :users, controllers: { sessions: 'users/sessions' }, :skip => [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :activities do
    get :autocomplete_client_name, :on => :collection
  end

  resources :models

  resources :industries

  resources :clients do
    resources :contacts
  end
  resources :outsiders
  get 'prospects/unassigned' => 'prospects#unassigned'
  get 'prospects/assignedoutsider' => 'prospects#assignedoutsider'
  get 'prospects/assignedrsm' => 'prospects#assignedrsm'
  get 'prospects/assignedcurrentrsm' => 'prospects#assignedcurrentrsm'
  resources :prospects do
    get :autocomplete_outsider_email, :on => :collection
    resources :contacts
    resources :outsiders
    resources :rsms
  end

  get 'prospects/convert_to_client/:id' => 'prospects#convert_to_client', :as => 'convert_prospect_to_client'
  get 'clients/archive/:id' => 'clients#archive', :as => 'archive_client'
  get 'clients/unarchive/:id' => 'clients#un_archive', :as => 'un_archive_client'
  get 'clients-archived' => 'clients#index_archived', :as => 'archived_clients'
  get 'clients/:id/reps/:user_id' => 'clients#show'
  root 'activities#index'
  get 'clients/:id/add-rsm-to-client' => 'clients#add_rsm_to_client', :as => 'add_rsm_to_client'
  get 'clients/:id/remove_rsm_from_client' => 'clients#remove_rsm_from_client', :as => 'remove_rsm_from_client'
  get 'prospects/:id/remove_rsm_from_prospect' => 'prospects#remove_rsm_from_prospect', :as => 'remove_rsm_from_prospect'
  get '/auditlogs' => 'audit_logs#index'

end

app/models/industry.rb
# == Schema Information
#
# Table name: industries
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime
#  updated_at :datetime
#

class Industry < ActiveRecord::Base
  validates :name, :presence => true
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
  before_action :hide_from_marketing
  before_action :set_industry, only: [:show, :edit, :update, :destroy]
  before_action :set_tab

  # GET /industries
  # GET /industries.json
  def index
    @industries = Industry.all.order("name")
  end

  # GET /industries/1
  # GET /industries/1.json
  def show
    if current_user.admin?
      @industry_clients = Client.where(:industry => @industry.id.to_s).uniq.order("name")
    else
      @industry_clients = current_user.clients.where(:industry => @industry.id.to_s).uniq.order("name")
    end
  end

  # GET /industries/new
  def new
    @industry = Industry.new
  end

  # GET /industries/1/edit
  def edit
  end

  # POST /industries
  # POST /industries.json
  def create
    @industry = Industry.new(industry_params)
    if current_user.admin?
      respond_to do |format|
        if @industry.save
          format.html { redirect_to industries_path, notice: 'Industry was successfully created.' }
          format.json { render :show, status: :created, location: @industry }
        else
          format.html { render :new }
          format.json { render json: @industry.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to industry_path(@industry), alert: 'You must be an admin to create an industry.'
    end
  end

  # PATCH/PUT /industries/1
  # PATCH/PUT /industries/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @industry.update(industry_params)
          format.html { redirect_to industries_path, notice: 'Industry was successfully updated.' }
          format.json { render :show, status: :ok, location: @industry }
        else
          format.html { render :edit }
          format.json { render json: @industry.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to industry_path(@industry), alert: 'You must be an admin to update an industry.'
    end
  end

  # DELETE /industries/1
  # DELETE /industries/1.json
  def destroy
    if current_user.admin?
      @industry.destroy
      respond_to do |format|
       format.html { redirect_to industries_url, notice: 'Industry was successfully destroyed.' }
       format.json { head :no_content }
      end
    else
      redirect_to industry_path(@industry), alert: 'You must be an admin to delete an industry.'
    end
  end

  private
    def hide_from_marketing
      if current_user.marketing? && !current_user.admin?
        redirect_to prospects_path, :alert => "Not authorized. Users who are in the marketing role may not access industries."
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end

    def set_tab
      @tab = "Industries"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def industry_params
      params.require(:industry).permit(:name)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_for @industry, :html => {:class => "form", :role => "form"}  do |f| %>
  <% if @industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% @industry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= button_tag(type: 'submit', :class => "btn btn-primary") do %>
      <i class="fas fa-check"></i> Save
    <% end %>
    <%= link_to industries_path, :class => "btn btn-default" do %>
      <i class="fas fa-times"></i> Cancel
    <% end %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<h2>Editing industry</h2>

<%= render 'form' %>

app/views/industries/index.html.erb
<h2>Industries</h2>
<% if current_user.admin? %>
  <p><%= link_to 'New Industry', new_industry_path, :class => "btn btn-primary" %></p>
<% end %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last updated</th>
    </tr>
  </thead>
  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= link_to industry.name, industry %></td>
        <td><%= industry.updated_at.strftime("%m/%d/%Y %I:%M %P %Z")  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/industries/new.html.erb
<h2>New industry</h2>

<%= render 'form' %>

app/views/industries/show.html.erb
<h2>Industry</h2>

<p>
  <strong>Name:</strong>
  <%= @industry.name %>
</p>

<% if @industry_clients.any? %>
<h3>Clients in this industry:</h3>
  <ul>
    <% @industry_clients.each do |client| %>
      <li><%= link_to client.name, client %></li>
    <% end %>
  </ul>
<% end %>

<p>
  <% if current_user.admin? %>
    <%= link_to edit_industry_path(@industry), :class => "btn btn-primary" do %>
      <i class="fas fa-pencil-alt"></i> Edit
    <% end %>
  <% end %>
  <%= link_to industries_path, :class => "btn btn-default" do %>
    <i class="fas fa-chevron-left"></i> Back
  <% end %>
</p>