config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  resources :settings

  resources :appointments

  get 'appointments/by-date/:appt_date' => 'appointments#by_date', :as => 'appointments_by_date'

  get '/calendar' => 'calendar#show'

  get 'reps/show'

  get 'profiles/reset_password/:id' => 'profiles#reset_password', :as => 'reset_user_password'
  resources :profiles

  namespace :profiles do
    namespace :move do
      get  :new
      post :create
    end
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password
  # devise_for :users, :skip => [:registrations]

  # https://github.com/plataformatec/devise#configuring-controllers
  devise_for :users, controllers: { sessions: 'users/sessions' }, :skip => [:registrations]

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :activities do
    get :autocomplete_client_name, :on => :collection
  end

  resources :models

  resources :industries

  resources :clients do
    resources :contacts
  end
  resources :outsiders
  get 'prospects/unassigned' => 'prospects#unassigned'
  get 'prospects/assignedoutsider' => 'prospects#assignedoutsider'
  get 'prospects/assignedrsm' => 'prospects#assignedrsm'
  get 'prospects/assignedcurrentrsm' => 'prospects#assignedcurrentrsm'
  resources :prospects do
    get :autocomplete_outsider_email, :on => :collection
    resources :contacts
    resources :outsiders
    resources :rsms
  end

  get 'prospects/convert_to_client/:id' => 'prospects#convert_to_client', :as => 'convert_prospect_to_client'
  get 'clients/archive/:id' => 'clients#archive', :as => 'archive_client'
  get 'clients/unarchive/:id' => 'clients#un_archive', :as => 'un_archive_client'
  get 'clients-archived' => 'clients#index_archived', :as => 'archived_clients'
  get 'clients/:id/reps/:user_id' => 'clients#show'
  root 'activities#index'
  get 'clients/:id/add-rsm-to-client' => 'clients#add_rsm_to_client', :as => 'add_rsm_to_client'
  get 'clients/:id/remove_rsm_from_client' => 'clients#remove_rsm_from_client', :as => 'remove_rsm_from_client'
  get 'prospects/:id/remove_rsm_from_prospect' => 'prospects#remove_rsm_from_prospect', :as => 'remove_rsm_from_prospect'
  get '/auditlogs' => 'audit_logs#index'

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :integer          not null, primary key
#  client_id     :integer
#  activity_date :datetime
#  contact_id    :integer
#  city          :string
#  state         :string
#  industry      :string
#  comments      :text
#  created_at    :datetime
#  updated_at    :datetime
#  user_id       :integer
#  attachment    :string
#

class Activity < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_activities, :against => [:city, :state, :comments]
  mount_uploader :attachment, AttachmentUploader
  has_many :activity_attachments, dependent: :destroy
  accepts_nested_attributes_for :activity_attachments
  belongs_to :client
  belongs_to :contact
  belongs_to :user
  has_and_belongs_to_many :models
  validates :client, :presence => true
  validates :activity_date, :presence => true

  def user_name
    return user.user_name
  end

  def self.create_from_import(activity_params)
    match_params = {activity_date: activity_params[:activity_date].in_time_zone("Eastern Time (US & Canada)"), client_id: activity_params[:client_id]}
    existing_activity = Activity.find_by(match_params)
    if existing_activity.nil?
      Activity.create(activity_params)
    else
      existing_activity
    end
  end

  def self.as_csv
    CSV.generate do |csv|
      x = column_names + ["contact_email", "users_email", "clients_name", "clients_eid", "models_name", "activity_attachments"]
      csv << x
      all.each do |item|
        y = item.attributes.values_at(*column_names) + [item.contact.nil? ? "" : item.contact.email] + [item.user.nil? ? "" : item.user.email] + [item.client.nil? ? "" : item.client.name] + [item.client.nil? ? "" : item.client.eid] + [item.models.pluck("name").join(",")] + [item.activity_attachments.pluck("attachment").join(",")]
        csv << y
      end
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  admin                  :boolean          default(FALSE)
#  role                   :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :recoverable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :recoverable
  has_many :activities
  has_many :appointments
  has_and_belongs_to_many :clients
  has_one  :profile
  after_create :create_child_profile

  def create_child_profile
    self.build_profile(:first_name => "", :last_name => "")
    self.profile.save!
  end

  def user_name
    if self.profile && self.profile.first_name.present?
      return "#{self.profile.first_name} #{self.profile.last_name}"
    else
      return self.email
    end
  end

  def active_clients
    self.clients.where(status:'Active').where(client_type:'Client')
  end

  def active_prospects
    return self.clients.where(status:'Active').where(client_type: 'Prospect')
  end

  def marketing?
    if self.role == "Marketing"
      return true
    else
      return false
    end
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :hide_from_marketing
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_tab
  autocomplete :client, :name, :extra_data => [:city,:state,:country], :display_value => :name_and_location

  # Scope autocomplete to clients for that user
  def get_autocomplete_items(parameters)
    items = super(parameters)
    if current_user.admin?
      items
    else
      items.includes(:users).where(users:{id: current_user.id})
    end
  end

  def index
    if current_user.admin?
      @activities = Activity.all.order("activity_date DESC").page params[:page]
    else
      @activities = current_user.activities.order("activity_date DESC").page params[:page]
    end
  end

  # GET /activities/1
  def show
    if current_user.activity_ids.include?(params[:id].to_i)
      @activity = current_user.activities.find(params[:id])
    elsif current_user.admin?
      @activity = Activity.find(params[:id])
    else
      redirect_to root_path, :alert => "Not authorized"
    end
    @activity_attachments = @activity.activity_attachments.all
  end

  def new
    if params[:client].present?
      @client = Client.find(params[:client])
    else
      @client = Client.new
    end
    if current_user.admin?
      @clients = Client.all.order(:name,:city)
    else
      @clients = current_user.clients.all.order(:name,:city)
    end
    @activity = Activity.new(:activity_date => Date.today)
    @activity_attachment = @activity.activity_attachments.build
  end

  # GET /activities/1/edit
  def edit
    if current_user.activity_ids.include?(params[:id].to_i)
      @activity = current_user.activities.find(params[:id])
    elsif current_user.admin?
      @activity = Activity.find(params[:id])
    else
      redirect_to root_path, :alert => "Not authorized"
    end
    @client = @activity.client
    if current_user.admin?
      @clients = Client.all.order(:name,:city)
    else
      @clients = current_user.clients.all.order(:name,:city)
    end
  end

  def create
    @activity = Activity.new(activity_params)
    if valid_client_choice?
      # Allow save with no contact
      if params[:new_contact].present? && activity_params[:client_id].present?
        @client = Client.find(activity_params[:client_id])
        @contact = Contact.where(:name => params[:new_contact]).first_or_create
        @client.contacts << @contact
        @activity.update_attribute(:contact_id, @contact.id)
      end
      if @activity.save
        if !params[:activity_attachments].nil?
          params[:activity_attachments]['attachment'].each do |a|
            @activity_attachment = @activity.activity_attachments.create!(:attachment => a)
          end
        end
        current_user.activities << @activity
        if params[:activity][:models].present?
          @model = Model.find(params[:activity][:models])
          @activity.models << @model
        end
        redirect_to activities_path, notice: 'Activity was successfully created.'
      else
        if activity_params[:client_id].present?
          @client = Client.find(activity_params[:client_id])
        else
          @client = Client.new
        end
        render :new
      end
    else
      if activity_params[:client_id].present?
        @client = Client.find(activity_params[:client_id])
      else
        @client = Client.new
      end
      @activity.errors[:base] << "The client you entered '#{params[:client_name]}' doesn't exist yet. Please choose from the existing clients or create a new client first. Then retry."
      render :new
    end
  end

  def create_old
    # Verify client exists first because of the type-ahead
    @client = Client.find(params[:client_id_val])
    if @client.nil?
      @activity.errors[:base] = "The client you entered '#{params[:client_id_val]}' doesn't exist yet. Please create the client first."
      render :new
    else
      # Allow save with no contact
      @activity = Activity.new(activity_params.merge(:client_id => params[:client_id_val]))
      if params[:new_contact].present? && params[:client_id_val].present?
        @client = Client.find(params[:client_id_val])
        @contact = Contact.where(:name => params[:new_contact]).first_or_create
        @client.contacts << @contact
        @activity.update_attribute(:contact_id, @contact.id)
      end
      if @activity.save
        current_user.activities << @activity
        if params[:activity][:models].present?
          @model = Model.find(params[:activity][:models])
          @activity.models << @model
        end
        redirect_to activities_path, notice: 'Activity was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    # Verify client exists first because of the type-ahead
    if !valid_client_choice?
      @activity.errors[:base] = "The client you entered '#{params[:client_name]}' doesn't exist yet. Please choose from the existing clients or create a new client first. Then retry."
      render :edit
    else
      if @activity.update(activity_params)
        if !params[:remove_activity_attachments].nil?
          params[:remove_activity_attachments].each do |aa_id|
            aa = @activity.activity_attachments.find(aa_id)
            aa.destroy
          end
        end
        if !params[:activity_attachments].nil?
          params[:activity_attachments]['attachment'].each do |a|
            @activity_attachment = @activity.activity_attachments.create!(:attachment => a)
          end
        end
        if params[:activity][:models].present?
          @model = Model.find(params[:activity][:models])
          @activity.models << @model
        end
        if params[:new_contact].present?
          @client = Client.find(params[:activity][:client_id])
          @contact = Contact.where(:name => params[:new_contact]).first_or_create
          @client.contacts << @contact
          @activity.update_attribute(:contact_id, @contact.id)
        end
        redirect_to activities_path, notice: 'Activity was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    if current_user.activity_ids.include?(params[:id].to_i)
      @activity = current_user.activities.find(params[:id])
    elsif current_user.admin?
      @activity = Activity.find(params[:id])
    else
      redirect_to root_path, :notice => "Not authorized"
    end
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def hide_from_marketing
    if current_user.marketing? && !current_user.admin?
      redirect_to prospects_path, :alert => "Not authorized. Users who are in the marketing role may not access activities."
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_tab
    @tab = "Activities"
  end

  def valid_client_choice?
    if params[:client_name].present? && activity_params[:client_id].present?
      @client = Client.find(activity_params[:client_id])
      if @client.name_and_location == params[:client_name]
        return true
      else
        return false
      end
    elsif activity_params[:client_id].present?
      @client = Client.find(activity_params[:client_id])
      return true
    else
      return false
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_params
    params.require(:activity).permit(:attachment_cache, :client_id, :activity_date, :contact_id, :city, :remove_activity_attachments, :state, :industry, :comments, activity_attachment_attributes: [:id, :activity_id, :attachment])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def attachment_is_image?
    if @activity.attachment_url.present?
      return /(.+\.(?:png|jpg|gif|jpeg|icon))/i.match(@activity.attachment_url)
    end
    return false
  end

end

app/views/activities/_form.html.erb
<%= form_for @activity, :html => {:class => "form", :role => "form", :multipart => true} do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>
      <ul>
        <% @activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :activity_date %>
    <%= f.text_field :activity_date, :type => "date", :class => "form-control", :value => @activity.activity_date.nil? ? "" : @activity.activity_date.to_date %>
  </div>
  <div class="form-group">
    <%= f.label :client_id %>
    <% if @activity.client %>
      <%= autocomplete_field_tag 'client_name', '', autocomplete_client_name_activities_path, :update_elements => {}, :class => "form-control", :value => @activity.client.name_and_location %>
    <% else %>
      <%= autocomplete_field_tag 'client_name', '', autocomplete_client_name_activities_path, :update_elements => {}, :class => "form-control", :placeholder => "Start typing in the client company name and choose the client" %>
    <% end %>
    <%= f.hidden_field :client_id %>
  </div>
  <div class="form-group">
    <%= f.label :contact_id, "Choose a contact" %>
    <% if @activity.contact %>
      <%= f.select :contact_id, options_from_collection_for_select(@client.contacts.order(:name), :id, :name, @activity.contact.id), {:include_blank => true}, {:class => "form-control"} %>
    <% elsif @client.nil? %>
      <%= f.select :contact_id, "", {:include_blank => true}, {:class => "form-control"} %>
    <% else %>
      <%= f.select :contact_id, options_from_collection_for_select(@client.contacts.order(:name), :id, :name), {:include_blank => true}, {:class => "form-control"} %>
    <% end %>
    <%= label_tag "new_contact", "or enter a new contact" %>
    <%= text_field_tag "new_contact", "", {:class => "form-control"}  %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.select :state, options_for_select(us_states,@activity.state), {:include_blank => true}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :industry %>
    <%= f.select :industry, options_from_collection_for_select(Industry.all.order(:name), :id, :name, @activity.industry), {:include_blank => true}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :models %>
    <%= f.select :models, options_from_collection_for_select(Model.all.order(:name), :id, :name, @activity.models), {:include_blank => true}, {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :comments %>
    <%= f.text_area :comments, :class => "form-control", :rows => "3" %>
  </div>
  <div class="field" style="margin-bottom:1em;">
    <%= f.label :attachment, "Attach file(s) (optional)" %><br>
    <%= f.file_field :attachment, :multiple => true, name: "activity_attachments[attachment][]" %>
  </div>
  <% if @activity.activity_attachments.count > 0 %>
    <table style="border-top:1px solid #ccc;margin-bottom:1em;">
      <% @activity.activity_attachments.each do |aa| %>
        <tr>
          <td style="padding:0.5em; border-bottom:1px solid #ccc;">
            <%= link_to File.basename(aa.attachment_url), aa.attachment_url, :target => "_blank" %>
            <%= "[#{number_to_human_size(File.size(aa.attachment.current_path))}]" %>
          </td>
          <td style="padding:0.5em; border-bottom:1px solid #ccc;">
            <label>
              <%= check_box_tag "remove_activity_attachments[]", aa.id %>
              Remove attachment
            </label>
          </td>
        </tr>
      <% end %>
    </table>
  <% end %>
  <div class="form-group">
    <%= button_tag(type: 'submit', :class => "btn btn-primary") do %>
      <i class="fas fa-check"></i> Save
    <% end %>
    <%= link_to activities_path, :class => "btn btn-default" do %>
      <i class="fas fa-times"></i> Cancel
    <% end %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h2>Editing activity</h2>

<%= render 'form' %>

app/views/activities/index.html.erb
<h2>Activities</h2>
<p><%= link_to 'New Activity', new_activity_path, :class => "btn btn-primary" %></p>
<% @activities.each do |activity| %>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <%= link_to activity.activity_date.to_date, activity %>
      <% if activity && activity.activity_attachments.empty? && activity.attachment_url.present? %>
        <i class="fas fa-paperclip"></i>
      <% end %>
      <% activity.activity_attachments.each do %>
        <i class="fas fa-paperclip"></i>
      <% end %>
    </div>
    <div class="panel-body">
      <p>
        <%= activity.client.name %>:
        <% if !activity.contact.nil? %>
          <%= activity.contact.name %><br>
        <% end %>
        <%= activity.comments %><br>
        <% if current_user.admin? %>
          Submitted by <%= activity.user_name %> on <%= activity.created_at.strftime("%m/%d/%Y %I:%M %P %Z") %>
        <% end %>
      </p>
    </div>
  </div>
<% end %>
<div style="background:#F5F5F5;padding:0 10px;border-radius:5px;">
  <%= paginate @activities %>
</div>

app/views/activities/new.html.erb
<h2>New activity</h2>

<%= render 'form' %>

app/views/activities/show.html.erb
<h2>Activity</h2>
<h3>Submitted by <%= @activity.user_name %> on <%= @activity.created_at.strftime("%m/%d/%Y %I:%M %P %Z") %></h3>
<table class="table">
  <tbody>
    <tr>
      <td>Date</td>
      <td> <%= @activity.activity_date.strftime("%m/%d/%Y") %></td>
    </tr>
    <tr>
      <td>Client</td>
      <td> <%= link_to @activity.client.name, @activity.client %></td>
    </tr>
    <tr>
      <td>Contact</td>
      <td>
        <% if !@activity.contact.nil? %>
          <%= @activity.contact.name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Industry
      </td>
      <td>
        <% if @activity.industry.present? %>
          <%= Industry.find(@activity.industry).name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Model
      </td>
      <td>
        <% if @activity.models.any? %>
          <%= Model.find(@activity.models.first).name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>Comments</td>
      <td><%= @activity.comments %></td>
    </tr>
    <% @activity.activity_attachments.each do |aa| %>
      <tr>
        <td>Attachment</td>
        <td>
          <%= link_to File.basename(aa.attachment_url), aa.attachment_url, :target => "_blank" %>
          <%= "[#{number_to_human_size(File.size(aa.attachment.current_path))}]" %>
          <% if attachment_is_image? %>
            <br/>
            <%= image_tag(aa.attachment_url, :width => 50) %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <% if @activity.activity_attachments.empty? && @activity.attachment_url.present? %>
      <tr>
        <td>Attachment</td>
        <td>
          <%= link_to File.basename(@activity.attachment_url), @activity.attachment_url, :target => "_blank" %>
          <%= "[#{number_to_human_size(File.size(@activity.attachment.current_path))}]" %>
          <% if attachment_is_image? %>
            <br/>
            <%= image_tag(@activity.attachment_url, :width => 50) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>
<p>
  <%  if current_user.activity_ids.include?(params[:id].to_i) || current_user.admin? %>
    <%= link_to edit_activity_path(@activity), :class => "btn btn-primary" do %>
      <i class="fas fa-pencil-alt"></i> Edit
    <% end %>
  <% end %>
  <%= link_to :back, :class => "btn btn-default" do %>
    <i class="fas fa-chevron-left"></i> Back
  <% end %>
</p>